/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rescateanimal.Views.Login;

import java.awt.Event;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.InputMap;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import rescateanimal.Controllers.CORREO_ELECTRONICO;
import rescateanimal.Controllers.ConexionLogin;
import rescateanimal.Models.codigo_recuperacion;
import rescateanimal.Validar;

/**
 *
 * @author ELIETH COLINDRES
 */
public class Codigo_Confirmacion extends javax.swing.JFrame {

    /**
     * Creates new form Codigo_Confirmacion
     */
    public Codigo_Confirmacion() {
        initComponents();
        this.setLocationRelativeTo(null); 
         this.lbl_Error.setVisible(false);
          InputMap map1 = this.txt_digito1.getInputMap(JTextField.WHEN_FOCUSED);
        map1.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
         InputMap map2 = this.txt_digito2.getInputMap(JTextField.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
         InputMap map3 = this.txt_digito3.getInputMap(JTextField.WHEN_FOCUSED);
        map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
         InputMap map4 = this.digito4.getInputMap(JTextField.WHEN_FOCUSED);
        map4.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_digito1 = new javax.swing.JTextField();
        txt_digito2 = new javax.swing.JTextField();
        txt_digito3 = new javax.swing.JTextField();
        digito4 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btn_confirmar = new javax.swing.JButton();
        lbl_Error = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(241, 242, 240));

        txt_digito1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_digito1KeyTyped(evt);
            }
        });

        txt_digito2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_digito2KeyTyped(evt);
            }
        });

        txt_digito3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_digito3ActionPerformed(evt);
            }
        });
        txt_digito3.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txt_digito3KeyTyped(evt);
            }
        });

        digito4.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                digito4KeyTyped(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(33, 67, 122));
        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(33, 67, 122));
        jLabel1.setText("Codigo de Confirmación");

        btn_confirmar.setText("Confirmar");
        btn_confirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_confirmarActionPerformed(evt);
            }
        });

        lbl_Error.setFont(new java.awt.Font("Dialog", 2, 12)); // NOI18N
        lbl_Error.setForeground(new java.awt.Color(102, 0, 0));
        lbl_Error.setText("Error en el codigo ingresado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(177, 177, 177)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txt_digito1, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_confirmar)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(txt_digito2, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lbl_Error))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(txt_digito3, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(digito4, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(112, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(84, 84, 84)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txt_digito1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_digito2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_digito3, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(digito4, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbl_Error)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                .addComponent(btn_confirmar)
                .addGap(30, 30, 30))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txt_digito1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_digito1KeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        int limite = 1;

        if(txt_digito1.getText().length() == limite) {

            evt.consume();

        }

    }//GEN-LAST:event_txt_digito1KeyTyped

    private void txt_digito2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_digito2KeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        int limite = 1;

        if(txt_digito2.getText().length() == limite) {

            evt.consume();

        }
    }//GEN-LAST:event_txt_digito2KeyTyped

    private void txt_digito3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_digito3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_digito3ActionPerformed

    private void txt_digito3KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txt_digito3KeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        int limite = 1;

        if(txt_digito3.getText().length() == limite) {

            evt.consume();

        }
    }//GEN-LAST:event_txt_digito3KeyTyped

    private void digito4KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_digito4KeyTyped
        // TODO add your handling code here:
        char car = evt.getKeyChar();

        int limite = 1;

        if(digito4.getText().length() == limite) {

            evt.consume();

        }
    }//GEN-LAST:event_digito4KeyTyped
ArrayList<codigo_recuperacion> codigo_recuperacion;
  ConexionLogin con = new ConexionLogin();
    private void btn_confirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_confirmarActionPerformed
        // TODO add your handling code here:
        int cont=0;
        Validar val=new Validar();
        val.evitarPegar(this.txt_digito1);
        val.evitarPegar(this.txt_digito2);
         val.evitarPegar(this.txt_digito3);
        val.evitarPegar(digito4);
       String respuesta;
       Boolean veri=false;
        ConexionLogin con=new ConexionLogin();
        con.buscarCodigo();
        respuesta=this.txt_digito1.getText()+this.txt_digito2.getText()+this.txt_digito3.getText()+this.digito4.getText();
                    this.codigo_recuperacion = this.con.buscarCodigo();
        for(int i=0;i<codigo_recuperacion.size();i++){
            if(codigo_recuperacion.get(i).getCodigo().equals(respuesta)){
                veri=true;
            }
        }
        if(veri==true){
             this.lbl_Error.setVisible(false);
            System.out.println("si");
        }else{
            this.lbl_Error.setVisible(true);
            System.out.println("no");
        }
        
    }//GEN-LAST:event_btn_confirmarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Codigo_Confirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Codigo_Confirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Codigo_Confirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Codigo_Confirmacion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Codigo_Confirmacion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_confirmar;
    private javax.swing.JTextField digito4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lbl_Error;
    private javax.swing.JTextField txt_digito1;
    private javax.swing.JTextField txt_digito2;
    private javax.swing.JTextField txt_digito3;
    // End of variables declaration//GEN-END:variables
}
