/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rescateanimal.Views.Login;

import com.placeholder.PlaceHolder;
import java.awt.Color;
import java.awt.Event;
import java.awt.event.KeyEvent;
import javax.swing.InputMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import rescateanimal.Controllers.CORREO_ELECTRONICO;
import rescateanimal.Controllers.Conexion;
import rescateanimal.Validar;

/**
 *
 * @author ELIETH COLINDRES
 */
public class Inicio_Sesion extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_Sesion
     */
    public Inicio_Sesion() {
        initComponents();
         this.setLocationRelativeTo(null); 
             PlaceHolder holder = new PlaceHolder(this.txtUsuario, "Usuario");
        PlaceHolder holder1 = new PlaceHolder(this.txtpassword, "Contraseña");
        this.lbl_error_usuario.setVisible(false);
         this.lbl_error_contra.setVisible(false);
         this.lbl_ambos_erroes.setVisible(false);
        CORREO_ELECTRONICO CO=new CORREO_ELECTRONICO();
       
         
        
        Conexion con=new Conexion();
                
        System.out.println(con.conector());
         InputMap map2 = this.txtUsuario.getInputMap(JTextField.WHEN_FOCUSED);
        map2.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
         InputMap map3 = this.txtpassword.getInputMap(JTextField.WHEN_FOCUSED);
        map3.put(KeyStroke.getKeyStroke(KeyEvent.VK_V, Event.CTRL_MASK), "null");
        
    }
  
   int cont=0,rep=0,seg1;
   String veri;
        String repetido = null;
    
      
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        txtpassword = new javax.swing.JPasswordField();
        txtUsuario = new javax.swing.JTextField();
        btn_ingresar = new javax.swing.JButton();
        btn_Salir = new javax.swing.JButton();
        lbll_recuperarcontra = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lbl_error_usuario = new javax.swing.JLabel();
        lbl_error_contra = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lbl_ambos_erroes = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel2.setBackground(new java.awt.Color(33, 67, 122));
        jPanel2.setForeground(new java.awt.Color(33, 67, 122));

        jLabel3.setBackground(new java.awt.Color(33, 67, 122));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(241, 242, 240));
        jLabel3.setText("Inicio de Sesión");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addGap(160, 160, 160))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel3)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel1.setBackground(new java.awt.Color(241, 242, 240));
        jPanel1.setForeground(new java.awt.Color(241, 242, 240));

        txtpassword.setBorder(null);

        txtUsuario.setBorder(null);
        txtUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtUsuarioActionPerformed(evt);
            }
        });

        btn_ingresar.setText("Ingresar");
        btn_ingresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_ingresarActionPerformed(evt);
            }
        });

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        lbll_recuperarcontra.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        lbll_recuperarcontra.setForeground(new java.awt.Color(0, 171, 197));
        lbll_recuperarcontra.setText("¿Olvidaste tu contraseña?");
        lbll_recuperarcontra.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lbll_recuperarcontra.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbll_recuperarcontraMouseMoved(evt);
            }
        });
        lbll_recuperarcontra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbll_recuperarcontraMouseClicked(evt);
            }
        });
        lbll_recuperarcontra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                lbll_recuperarcontraKeyPressed(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Universidad\\POO\\Parcial 3\\Rescate_Annimal\\user_icon-icons.com_66546.png")); // NOI18N

        lbl_error_usuario.setForeground(new java.awt.Color(153, 0, 0));
        lbl_error_usuario.setText("Ingrese Usuario");

        lbl_error_contra.setForeground(new java.awt.Color(153, 0, 0));
        lbl_error_contra.setText("Ingrese contraseña");

        jLabel4.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELIETH COLINDRES\\Downloads\\image.png")); // NOI18N

        lbl_ambos_erroes.setForeground(new java.awt.Color(153, 0, 0));
        lbl_ambos_erroes.setText("Error en el usuario o contraseña");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\ELIETH COLINDRES\\Downloads\\Gender_Neutral_User_icon-icons.com_55902.png")); // NOI18N

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(124, 124, 124))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbll_recuperarcontra))
                            .addGap(24, 24, 24))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(lbl_error_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lbl_error_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(44, 44, 44)))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(157, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(182, 182, 182))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(154, 154, 154))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(lbl_ambos_erroes)
                        .addGap(139, 139, 139))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbl_ambos_erroes)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 11, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtUsuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_error_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_error_contra, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jLabel4))
                .addGap(18, 18, 18)
                .addComponent(lbll_recuperarcontra)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btn_ingresar, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(btn_Salir, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtUsuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtUsuarioActionPerformed
    String [] arreglo1 = new String [10]; 

    private void btn_ingresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_ingresarActionPerformed
        // TODO add your handling code here:

        Boolean ver,min=true;
        Validar val=new Validar();
        Conexion co=new Conexion();
        
        ver=co.validlog(this.txtUsuario.getText(), this.txtpassword.getText());
         val.evitarPegar(txtUsuario);
         val.evitarPegar(this.txtpassword);
         if(val.Usuariomin(txtUsuario.getText())==false){
             JOptionPane.showMessageDialog(null, "Debe ingresar caracteres mayor que 4");
             min=false;
         }
         if(val.Contramin(txtpassword.getText())==false){
             JOptionPane.showMessageDialog(null, "Debe ingresar caracteres mayor que 8");
             min=false;
         }
        if(ver==true){
            System.out.println("SI");
        }else{
///ARREGLAR
            if(this.txtUsuario.getText().equals("Usuario")&&this.txtpassword.getText().equals("Contraseña")&&min==true){
               this.lbl_error_usuario.setVisible(true);
                     this.lbl_error_contra.setVisible(true);
                     this.lbl_ambos_erroes.setVisible(false);
            }else{
               
                     if(this.txtUsuario.getText().equals("Usuario")){
                    this.lbl_error_usuario.setVisible(true);
                     this.lbl_error_contra.setVisible(false);
                     this.lbl_ambos_erroes.setVisible(false);
                }else{
                     if(this.txtpassword.getText().equals("Contraseña")){
                         this.lbl_error_usuario.setVisible(false);
                          this.lbl_error_contra.setVisible(true);
                          this.lbl_ambos_erroes.setVisible(false);
                     }else{
                          if(ver==false&& repetido==null&&min==true){
                               this.lbl_error_usuario.setVisible(false);
                          this.lbl_error_contra.setVisible(false);
                          this.lbl_ambos_erroes.setVisible(true);
                            arreglo1[this.cont]=this.txtUsuario.getText();
                            
                            cont++;
                }    
                         
                     }
                }
                
               
            }
                   
            
            if(cont>2){
                for(int i=0;i<this.cont;i++){
                   if(arreglo1[i].equals(this.txtUsuario.getText())){
                        rep++;
                        repetido=this.txtUsuario.getText();
                    }
                    System.out.println(repetido);
                }        
                if(rep>3){
                    System.out.println("bloqueado");
                }else{
                    if(rep==3){
                        rep=0;
                        cont=0;

                    } else{
                            rep=0;
                            repetido=null;
                    } 
                       
                }
                       
            }
           
    }

     

    }//GEN-LAST:event_btn_ingresarActionPerformed

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btn_SalirActionPerformed

    private void lbll_recuperarcontraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbll_recuperarcontraMouseMoved
        // TODO add your handling code here:

        this.lbll_recuperarcontra.setForeground(Color.blue);

    }//GEN-LAST:event_lbll_recuperarcontraMouseMoved

    private void lbll_recuperarcontraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbll_recuperarcontraMouseClicked
        // TODO add your handling code here:

        Recuperacion rec=new Recuperacion();

        rec.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lbll_recuperarcontraMouseClicked

    private void lbll_recuperarcontraKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lbll_recuperarcontraKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_lbll_recuperarcontraKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_Sesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio_Sesion().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salir;
    private javax.swing.JButton btn_ingresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbl_ambos_erroes;
    private javax.swing.JLabel lbl_error_contra;
    private javax.swing.JLabel lbl_error_usuario;
    private javax.swing.JLabel lbll_recuperarcontra;
    private javax.swing.JTextField txtUsuario;
    private javax.swing.JPasswordField txtpassword;
    // End of variables declaration//GEN-END:variables
}
